BOT_TOKEN="ENTER HERE YOUR BOT TOKEN"
chat_ids = [ENTER HERE THE CODE GIVEN WITH COMMAND /start]
url = "YOUR OLLAMA URL ie: http://0.0.0.0.0:11434"
url2 = "YOUR SECONDARY OLLAMA URL IF WANTED"
model_name = "THE NAME OF YOUR MODEL"


